# Generated by Django 2.0 on 2022-06-08 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=20, verbose_name='Name')),
                ('start_date', models.DateField(default=datetime.datetime(2022, 6, 8, 5, 28, 55, 210851, tzinfo=utc), verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.datetime(2022, 6, 8, 5, 28, 55, 210851, tzinfo=utc), verbose_name='End Date')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Description')),
                ('salary', models.FloatField(default=0.0, verbose_name='Salary')),
            ],
        ),
    ]
