# Generated by Django 2.0 on 2022-06-08 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_jobs', '0001_initial'),
        ('sms_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='job_id',
            field=models.ManyToManyField(to='sms_jobs.JobModel'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 12, 36, 3, 955553, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 12, 36, 3, 955553, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
