# Generated by Django 2.0 on 2022-06-09 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_contracts', '0003_auto_20220608_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 7, 33, 13, 458749, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 7, 33, 13, 458749, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
