# Generated by Django 2.2 on 2022-08-18 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_contracts', '0005_auto_20220818_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='contract_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 7, 52, 58, 389148, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 7, 52, 58, 389148, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
