# Generated by Django 2.2 on 2022-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_jobs', '0002_jobmodel_expected_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_title',
            field=models.CharField(max_length=200, verbose_name='job_title'),
        ),
    ]
