# Generated by Django 2.0 on 2022-06-04 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('birthday', models.DateField(default=datetime.datetime(2022, 6, 4, 13, 38, 50, 54104, tzinfo=utc), verbose_name='Birthday')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='imgs/')),
            ],
        ),
    ]
