# Generated by Django 2.0 on 2022-06-04 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 4, 15, 22, 22, 832004, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
