# Generated by Django 2.0 on 2022-06-04 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0002_auto_20220604_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 4, 15, 29, 5, 954961, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
