# Generated by Django 2.0 on 2022-06-06 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0003_auto_20220604_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 6, 7, 45, 47, 596487, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
