# Generated by Django 2.0 on 2022-06-06 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0005_auto_20220606_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 6, 8, 22, 8, 915680, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
