# Generated by Django 2.0 on 2022-06-06 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0006_auto_20220606_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 6, 11, 54, 41, 306630, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
