# Generated by Django 2.0 on 2022-06-06 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0009_auto_20220606_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 6, 12, 31, 27, 326250, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
