# Generated by Django 2.0 on 2022-06-07 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0010_auto_20220606_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 7, 7, 45, 17, 151031, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
