# Generated by Django 2.0 on 2022-06-07 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0011_auto_20220607_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 7, 7, 52, 40, 799626, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
