# Generated by Django 2.0 on 2022-06-07 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0012_auto_20220607_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 7, 7, 54, 10, 282061, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
