# Generated by Django 2.0 on 2022-06-07 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0013_auto_20220607_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 7, 12, 36, 57, 151780, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
