# Generated by Django 2.0 on 2022-06-08 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_contracts', '0002_auto_20220608_1906'),
        ('sms_employees', '0014_auto_20220607_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='contract_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sms_contracts.ContractModel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 12, 36, 3, 955553, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
