# Generated by Django 2.2 on 2022-08-18 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms_employees', '0021_auto_20220818_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 11, 42, 54, 583398, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
